### ISSUE TITLE
Studio Controlls Crashing

### ISSUE THREAD

**Issue by Aladio** [ovenwerks/studio-controls#11]
Computer

Processor	Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
Memory	12213MB (2571MB used)
Machine Type	Desktop
Operating System	Ubuntu 20.10
Kernel	Linux 5.8.0-26-lowlatency (x86_64)
Version	#27-Ubuntu SMP PREEMPT Thu Oct 22 00:13:52 UTC 2020
C Library	GNU C Library / (Ubuntu GLIBC 2.32-0ubuntu3) 2.32
Distribution	Ubuntu 20.10

Crashes
1)
Oct 31 12:36:05 sparkyio.com /usr/libexec/gdm-x-session[4275]: (EE) client bug: timer event2 debounce: scheduled expiry is in the past (-8ms), your system is too slow
Oct 31 12:36:05 sparkyio.com /usr/libexec/gdm-x-session[4275]: (EE) client bug: timer event2 debounce short: scheduled expiry is in the past (-21ms), your system is too slow
Oct 31 12:36:19 sparkyio.com systemd[1919]: Started Application launched by gnome-shell.
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: Traceback (most recent call last):
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: File "/usr/bin/studio-controls", line 1197, in <module>
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: us = StudioControls()
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: File "/usr/bin/studio-controls", line 321, in init
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: jack.set_error_function(callback=self.jack_error)
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: File "/usr/lib/python3/dist-packages/jack.py", line 2835, in set_error_function
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: _set_error_or_info_function(callback, _lib.jack_set_error_function)
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: File "/usr/lib/python3/dist-packages/jack.py", line 2874, in _set_error_or_info_function
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: def callback_wrapper(msg):
Oct 31 12:36:20 sparkyio.com studio-controls.desktop[96011]: SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
Oct 31 12:36:20 sparkyio.com systemd[1919]: app-gnome-studio\x2dcontrols-96011.scope: Succeeded.
2)
Oct 31 14:41:42 sparky-lab systemd[1853]: Started Application launched by gnome-shell.
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: Traceback (most recent call last):
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: File "/usr/bin/studio-controls", line 1197, in <module>
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: us = StudioControls()
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: File "/usr/bin/studio-controls", line 321, in init
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: jack.set_error_function(callback=self.jack_error)
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: File "/usr/lib/python3/dist-packages/jack.py", line 2835, in set_error_function
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: _set_error_or_info_function(callback, _lib.jack_set_error_function)
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: File "/usr/lib/python3/dist-packages/jack.py", line 2874, in _set_error_or_info_function
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: def callback_wrapper(msg):
Oct 31 14:41:43 sparky-lab studio-controls.desktop[84250]: SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
Oct 31 14:41:43 sparky-lab systemd[1853]: app-gnome-studio\x2dcontrols-84250.scope: Succeeded.
Oct 31 14:41:53 sparky-lab systemd[1853]: Started Application launched by gnome-session-binary.
oh and I changed my hostname in case you are wondering
3)
The whole enchilada
https://termbin.com/bcj0b

**Comment by eeickmeyer** [comment]
Appears to be an issue from a change in python3-cffi per previous discussion.
