### ISSUE TITLE
jack_control only admits one command

### ISSUE THREAD

**Issue by Marzal** [ovenwerks/studio-controls#14]
Despite the advertised in the usage
`Usage: jack_control [command] [command] ...`
[jack_control](https://github.com/jackaudio/jack2/blob/develop/tools/jack_control) seems to only "use" the first command (+parameter)

I get this error with studio-controls
```
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
```
because [jack.Client](https://jackclient-python.readthedocs.io/en/0.5.3/api.html#jack.Client) try to use the default config instead of the config set with jack_control if `jack_control start` is not executed.

https://github.com/ovenwerks/studio-controls/blob/e6a1e44b402564d3f3267fe6e68eab82003b6d5a/usr/bin/autojack#L490
With `jack_control dp` it's easy to see that some parameters are not changing, but more important is that **start** is never executed.

```bash
jack_control dps period 1024 dps nperiods 3 start  
--- driver param set "period" -> "1024"

jack_control dp
--- get driver parameters (type:isset:default:value)
              device: ALSA device name (str:set:hw:0:hw:S,0,0)
             capture: Provide capture ports.  Optionally set device (str:notset:none:none)
            playback: Provide playback ports.  Optionally set device (str:notset:none:none)
                rate: Sample rate (uint:notset:48000:48000)
              period: Frames per period (uint:set:1024:1024)
            nperiods: Number of periods of playback latency (uint:notset:2:2)
               hwmon: Hardware monitoring, if available (bool:notset:False:False)
             hwmeter: Hardware metering, if available (bool:notset:False:False)
              duplex: Provide both capture and playback ports (bool:notset:True:True)
            softmode: Soft-mode, no xrun handling (bool:notset:False:False)
             monitor: Provide monitor ports for the output (bool:notset:False:False)
              dither: Dithering mode (char:notset:n:n)
          inchannels: Number of capture channels (defaults to hardware max) (uint:notset:0:0)
         outchannels: Number of playback channels (defaults to hardware max) (uint:notset:0:0)
              shorts: Try 16-bit samples before 32-bit (bool:notset:False:False)
       input-latency: Extra input latency (frames) (uint:notset:0:0)
      output-latency: Extra output latency (frames) (uint:notset:0:0)
         midi-driver: ALSA MIDI driver (str:notset:none:none)

jack_control status
--- status
stopped
```

Splitting each command fix my problem. I'm preparing a PR with a partial fix with something like this

```python
        cp = subprocess.run(["/usr/bin/jack_control", "dps", "period", def_config['FRAME'], 
                        universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False)
        logging.debug(f"Jackdbus: {cp.stdout.strip()}")
        cp = subprocess.run(["/usr/bin/jack_control", "dps", "nperiods", def_config['PERIOD']],
                        universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False)
        logging.debug(f"Jackdbus: {cp.stdout.strip()}")
        cp = subprocess.run(["/usr/bin/jack_control", "start"],
                        universal_newlines=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False)
        logging.debug(f"Jackdbus: {cp.stdout.strip()}")

```
that allows JACK to start properly. I'm no developer so probably there is a better way to refactor this, but anyway is a quick fix in the meantime

```
Acquired audio card Audio1
creating alsa driver ... hw:S,0|hw:S,0|1024|2|48000|1|2|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 16bit little-endian
```

jack2 1.9.16-1
python-jack-client 0.5.3-1
studio-controls-git 2.0.9.r9.gda40e90-1

**Comment by ovenwerks** [comment]
Two problems here. 1) when we open a jack client, we open with "no_start_server"... but it seems I was using C/C++ style calls and not python style, This is fixed. 2) the server start command needs some delay before it starts. I changed all calls to jack_control to direct dbus calls. Even though they were all separate, sometimes the dbus call would not complete, adding some delay seems to fix this. Please test latest git commit

**Comment by Marzal** [comment]
Thanks, JACK starts OK, bridges connected and there is  nothing strange in jackdbus.log or autojack.log.

I think this is fixed and the issue can be closed :smile:

**Comment by Marzal** [comment]
Just for the record, this was a bug en Jack2 and it's been fixed with this commit
https://github.com/jackaudio/jack2/commit/d39b886aa568cceb897ce73b71f67eca00b44667
