### ISSUE TITLE
Fedora 33: [abrt] studio-controls: user_audio(): studio-controls:41:user_audio:UnboundLocalError: local variable 'audio_users' referenced before assignment 

### ISSUE THREAD

**Issue by eeickmeyer** [ovenwerks/studio-controls#17]
Reported in Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=1895691

Description of problem:
Just open the app.

Version-Release number of selected component:
studio-controls-2.0.9-1.fc33

Additional info:
reporter:       libreport-2.14.0
cmdline:        /usr/bin/python3 /usr/bin/studio-controls
crash_function: user_audio
exception_type: UnboundLocalError
executable:     /usr/bin/studio-controls
interpreter:    python3-3.9.0-1.fc33.x86_64
kernel:         5.8.18-300.fc33.x86_64
runlevel:       N 5
type:           Python3
uid:            1000

Truncated backtrace:
studio-controls:41:user_audio:UnboundLocalError: local variable 'audio_users' referenced before assignment

Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1197, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 225, in __init__
    if self.jack_file_exists and self.sysinfo.user_audio():
  File "/usr/bin/studio-controls", line 41, in user_audio
    if user in audio_users:
UnboundLocalError: local variable 'audio_users' referenced before assignment

Local variables in innermost frame:
self: <__main__.SysInfo object at 0x7fe5da839160>
groups_file: <_io.TextIOWrapper name='/etc/group' mode='r' encoding='UTF-8'>
line: 'dnsmasq:x:963:\n'
user: 'yajo'
audio_group: False

User attempted to start after deleting ~/.config/autojack, same result.
See https://bugzilla.redhat.com/show_bug.cgi?id=1895691 for more information.

**Comment by Marzal** [comment]
I can reproduce the error if I delete (or change) the **audio** group in /etc/group.

No audio group could be the problem.

**Comment by yajo** [comment]
Then it happened because of how fedora silverblue deals with groups.

**Comment by eeickmeyer** [comment]
@Yajo You didn't specify in the original bug report that this was silverblue. Unfortunately, if silverblue has a different way of dealing with groups, then we can't support that. I'm tempted to close both bug reports as invalid, but I do want to know what @ovenwerks has to say.

@ovenwerks , in case you're not familiar, silverblue is a version of Fedora that has an immutable file system and mostly relies on flatpaks to deal with software installation. There are ways of installing standard Fedora packages via rpm-ostree, but not everything is guaranteed to work. What are your thoughts about supporting this flavor of OS?

**Comment by ovenwerks** [comment]
flatpacks and audio in general do not go together well. In a jack environment all jack applications and all plugins used by any of those applications must be a part of the same flatpack... I would guess one may as well create one big flatpack for the whole OS.

However, I am willing to add the pr for the fix... I expect that will keep it from crashing, but I am not as sure it will make studio_controls operate correctly in a flatpack, snaps, etc. based OS or distro. I will also add a warning to the README and INSTALL files that this software should never be packaged as a flatpack or snap or other sandbox style package, nor used with any audio applications installed that way.

**Comment by ovenwerks** [comment]
Fix applied

**Comment by Marzal** [comment]
With the new code studio-controls keep crashing upon launch and never start.
Initializing the variable was a fix with the old code, but right know if there is no **audio** group in the system I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1273, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 227, in __init__
    if self.jack_file_exists and self.sysinfo.user_audio():
  File "/usr/bin/studio-controls", line 35, in user_audio
    audio_users = grp.getgrnam("audio")[3]
KeyError: "getgrnam(): name not found: 'audio'"
```

**Comment by eeickmeyer** [comment]
@Marzal We can't add an audio group to the system, and an audio group is basically a prerequisite for this to work. Therefore, it is on the user or the distro to have the audio group already. This isn't a problem in Fedora or Ubuntu where an audio group exists by default, but in Arch, it's up to the user to configure their system correctly.

Basically, this isn't a bug anymore, but rather a system misconfiguration.

**Comment by Marzal** [comment]
Arch has an audio group thanks to /usr/lib/sysusers.d/basic.conf (I only found this because of the testing I did with this bug).
I think that the **audio** group is not really needed if you use the **realtime** group for RT, systemd and udev. But I was only reporting this to let you know of the outcome of the fix (even if is not really needed because is not a bug), in case is decided to really "catch" this possible crash.

I don't think that leaving this as it is would be a problem for Arch users, it was more for the sake of completeness in the bug report.

**Comment by yajo** [comment]
I think this is a bug in the sense that this is a GUI app. So, if it fails to start because the system is misconfigured, instead of raising an exception to the logs, it should open a dialog telling the user what's happening and how to fix it.

**Comment by eeickmeyer** [comment]
@Yajo That's not a bug then, that's a feature request. All *correctly* configured Linux systems should have an audio group by default. Without it, a lot of applications will cease to function correctly, not just this one.

That said, I don't think it's worth worrying about.
