### ISSUE TITLE
Difference between "system:playback1 and 2" and "Main Output Ports"?

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#19]
Trying to get the PulseAudio bridging working now. Even with the bridge settings enabled, the audio cuts off when JACK is started in -controls.

I'm wondering first though what the difference between the Auto Connect Port menu options of "system:playback1 and 2" and "Main Output Ports"? Are these the same?

**Comment by ovenwerks** [comment]
They can be the same (are the same by default) but Main output ports can be changed if for example, your device has main outputs on system:playback_9 and 10 like the spdif outs on a delta 1010 for example.
