### ISSUE TITLE
Capitalisation of JACK?

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#2]
In the app it's Jack, but officially and in most instances it's JACK, and possibly consistency is something that is desired?

**Comment by ovenwerks** [comment]
I am working on this as I add new GUI bits. Thank you for pointing it out. I use MIDI, JACK must be a blind spot.

**Comment by mxmilkiib** [comment]
Thank you :) The only ones I've noticed now are the "USB Jack Master" when the internal device is overridden, "Ports cannot be displayed unless Jack is running" in Extra Devices / Main Output Ports.

**Comment by ovenwerks** [comment]
Those should also be fixed, Thank you

**Comment by mxmilkiib** [comment]
Also in the sink name for Pulse. 
![image](https://user-images.githubusercontent.com/108225/102701897-dba9f700-4253-11eb-8d0b-e5761d525e54.png)

**Comment by Marzal** [comment]
I think that's from pulseaudio itself:

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/modules/jack/module-jack-source.c#L345

https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/modules/jack/module-jack-sink.c#L403

It can be overwriten with
`
sink_properties=device.description='"JACK\ Sink\ (client_name)"'
`
But I'm not sure it worth the trouble, it would be better to report it to pulseaudio directly.
In the rare case that the change is accepted, it will be really slow to see the effect ->
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/439

**Comment by Marzal** [comment]
I stand corrected, they already merged the change, now it's just waiting to a new pulseaudio release.
