### ISSUE TITLE
"Apply Audio Settings" is restarting JACK when changing buffer size (was: Add Cadence's "Switch to master")

### ISSUE THREAD

**Issue by Porrumentzio** [ovenwerks/studio-controls#24]
Studio Controls is a great tool for me, even more comfortable than Cadence. But Cadence has a feature that I would like to see on Studio Controls, which is the `Switch to master` option.
Clicking this makes the changed settings be applied **without** stopping JACK.

**Comment by eeickmeyer** [comment]
Hi @Porrumentzio ! This is exactly the purpose behind the "Apply Audio Settings" button, so can you be more specific about what this does?

**Comment by Porrumentzio** [comment]
On my case, Apply Audio Settings did stop JACK when changing from buffer size. It stops JACK and runs it automatically, but this is not as fast as Cadence, which does this so rapid that no change is seen. On Studio Controls, JACK is clearly stopped and the sound too, until it's again launched (1-2 seconds)

**Comment by eeickmeyer** [comment]
>On my case, Apply Audio Settings did stop JACK when changing from buffer size

Yeah, that's not supposed to happen. Sounds to me like you found a bug.

**Comment by Porrumentzio** [comment]
This also happens when changing to USB device, which also did not effectively change the output ports to USB with Apply Audio Settings

**Comment by eeickmeyer** [comment]
You shouldn't ever have to change USB device, Studio Controls can recognize and work with multiple audio devices simultaneously. All routing would be done via Carla's patchbay; Studio Controls doesn't have its own patchbay or any way of rerouting on the fly.

**Comment by Porrumentzio** [comment]
What I mean is that when plugging the USB device in, JACK is stopped

**Comment by eeickmeyer** [comment]
That also doesn't seem right, because that is handled by zita-ajbridge, not by studio-controls or autojack directly. We'll wait for @ovenwerks to comment on this because that's more his wheelhouse, but I believe that's two different bugs.

**Comment by Porrumentzio** [comment]
I opened #27, thanks @eeickmeyer!

**Comment by ovenwerks** [comment]
Switch master has been less than reliable. When studio-controls was first created it used switch master when a USB master was plugged or unplugged. In general in my experience, the first switch would work great... the second would freeze jackdbus requiring a kill -9 to get things working again. that bug was fixed by force restarting jackdbus each time. If there is a way to make switch master work correctly each and every time, I am all for it, but crashing jackdbus even once in a while is a show stopper.
