### ISSUE TITLE
Panel-icon missing on Manjaro MATE

### ISSUE THREAD

**Issue by Porrumentzio** [ovenwerks/studio-controls#26]
Although the app does have an icon on the menu-launcher, it doesn't on the panel: 
![irudia](https://user-images.githubusercontent.com/61913683/99555518-b5790900-29c0-11eb-9308-00b24a7234b5.png)

Happened same on here:
https://github.com/rafaelmardojai/blanket/issues/54

_____

This commit solved the issue for Blanket, a Gstreamer GTK app: https://github.com/rafaelmardojai/blanket/commit/b3d0f92f97286cd5055b6e7abba29a4adad0f568

**Comment by eeickmeyer** [comment]
Looks like this should theoretically solve the issue, if we can get it in the code:

```
        # Set default window icon for window managers
        self.set_default_icon_name('studio-controls')
```

**Comment by ovenwerks** [comment]
While I do not experience this problem in plasma, I have set the default icon in the code... hope fully it will reach this repo soon.

**Comment by ovenwerks** [comment]
This should be fixed in the latest upload please test.

**Comment by Porrumentzio** [comment]
I'll test when it will come to AUR :)
Thanks for the work!
