### ISSUE TITLE
segfault on start

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#3]
https://gist.github.com/mxmilkiib/aee65d0d964eea239de0f43a02fd6466

**Comment by ovenwerks** [comment]
Please try version 2.0.8

If there is still a problem, please set the debug level to "Extra" and rerun. Then send a copy of ~/.log/autojack.log in a comment.

**Comment by mxmilkiib** [comment]
Just rebuilt, studio-controls-git-2.0.4.r5.g2675e63-1, segfault coredump;
https://gist.github.com/e1d029b100ebca8498afe1d30029c92d

Sorry, how do you mean set the debug level to "Extra"? This is just `coredumpctl info studio-controls -1 | gist -p`

Edit: and I don't have an `~/.log/autojack.log`, last change in that folder was for the `ladish` dir two years ago.

**Comment by eeickmeyer** [comment]
Logging level is set within the interface itself (very first page).

Moreover, it seems as if you failed to follow instruction and rebuilt an older verison. Sorry, but your most recent comment is pretty useless. Please retry with the most recent tag.

**Comment by mxmilkiib** [comment]
I think someone didn't do the git release tag right or something. Edit: or the versioning scheme changed?

I put the full version produced by the [PKGBUILD pkgver()](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ubuntustudio-controls-git#n23) because it has the sha of the last commit `2675e63`. r5 means 5 commits after 2.0.4 was tagged.

The app crashes before I get a GUI.

**Comment by eeickmeyer** [comment]
The release tag is here: https://github.com/ovenwerks/studio-controls/releases/tag/2.0.8
The actual tag (which is created with git tag) is here: https://github.com/ovenwerks/studio-controls/releases/tag/2.0.8

If your PKGBUILD isn't pulling the tag, then this whole issue is a clear error in the packaging. Unfortunately, we cannot support Arch, so unless @ovenwerks objects and reopens, this issue is closed.

**Comment by mxmilkiib** [comment]
Ok, thanks, I have fixed the version string of the package;

```
pacman -Qi studio-controls-git
Name            : studio-controls-git
Version         : 2.0.8.r0.g2675e63-1
...
```

But as I implied regarding the sha, it is pulling and building `master` (as should all AUR entries ending `-git`).

**Comment by eeickmeyer** [comment]
That's fine, but there are multiple factors here, such as python-alsaaudio or python-jack-client being the wrong version among other issues. We simply cannot support Arch Linux.

**Comment by mxmilkiib** [comment]
Ok. Not sure why you didn't just state that initially, instead purportedly closing the issue over a detail that has no relation to the problem.

It's entirely fair if you(s) don't wish to support rolling release distros (or develop to current dep releases in a dev branch).

I decided to disown the AUR entry.

**Comment by eeickmeyer** [comment]
Let's start over. Sorry for my attitude.

**Comment by ovenwerks** [comment]
I would still like to see what 2.0.8 does. in your case. There are two things I would like to know: does ps x|grep autojack show it is running?
if you run studio-controls from command line, what output do you get? (if autojack is not running, can it be run from the command line and what errors show up?)

**Comment by mxmilkiib** [comment]
`autojack` segfaults when i try to run it. [coredump and strace](https://gist.github.com/mxmilkiib/aa342255aaab4925cb265986607bd2b9).

[Same](https://gist.github.com/mxmilkiib/b9c31f667ec89ac620cf18e9f63be5d4) for `studio-controls`.

Given I'm running on Arch and not Ubuntu Studio, might I be missing some additional setup factor? Or maybe it is just a differing lib api?

**Comment by ovenwerks** [comment]
So when you run on the command line there is no output aside from the core dump? Normally with python I would expect about 5 lines from python giving errors with file line numbers. I don't see anything outside of python itself. No extra libs or anything. The first thing it should do is import a group of extra libs and if any are not there I would expect a message on stderr saying what it was missing. The segfault seems to indicate it is within libpython3.8 or at a point it calls a function in libc.

Now that you have run it on the command line is there a file ~/log/autojack.log? If so please paste it. If not, then we at least know it has not made it far enough to open up the logfile. I would guess the next thing is to add a bunch of print("bp1") etc. lines to see how far it does make it. Are you comfortable adding these in your copy? or would you like me to send you another to try?

**Comment by mxmilkiib** [comment]
I've just pulled and tried again, and the segfault on start issue has been resolved.
