### ISSUE TITLE
Error on launch : chan-{in,out} int

### ISSUE THREAD

**Issue by Marzal** [ovenwerks/studio-controls#34]
Even with the last commit, without this change, studio-contrls wont start 
        self.chan_in_spin.set_value(**int**(self.jackdb['chan-in']))
        self.chan_out_spin.set_value(**int**(self.jackdb['chan-out']))

```bash
Config file: /home/dmc/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1437, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 445, in __init__
    self.chan_in_spin.set_value(self.jackdb['chan-in'])
TypeError: Must be number, not str

```

**Comment by ovenwerks** [comment]
This has been fixed, If it had made it past that there would be more errors :P
