### ISSUE TITLE
Extra devices: playback/capture port number widget mouse click speed problem

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#38]
When clicking the plus and minus for both the capture and playback number picker widgets, clicking really fast makes it skip certain numbers.

**Comment by ovenwerks** [comment]
This does not seem to be adjustable from within gtk

**Comment by mxmilkiib** [comment]
This should be an issue upstream then I guess. Could you please describe the problem in technical terms so one could be made. Thanks :)
