### ISSUE TITLE
Makefile typo? Missing "/" in  "everything else is"

### ISSUE THREAD

**Issue by Elkenfugel** [ovenwerks/studio-controls#44]
https://github.com/ovenwerks/studio-controls/blob/11af07b79356db5f6c92325b98886e54ade97ecb/Makefile#L48

In the make file, the path to the install files is missing the root "/" ?
Am I correct? I tried "sudo make install" from a git clone and nothign was working and i noticed that all of those files that are echo'd are not present in my ubuntu 20.10. I edited my own make file but i am unsure how to proceed with fixing it here. please help me!
Lines affected : 49-89

**Comment by Elkenfugel** [comment]
Also on line 23-24

**Comment by ovenwerks** [comment]
Those lines are correct. The paths are relative to the install directory for the source files and the destination files have the root / built in in $PREFIX
