### ISSUE TITLE
pulse bridge unique name is not enough

### ISSUE THREAD

**Issue by Marzal** [ovenwerks/studio-controls#49]
Just to know if this is the desired behavior.
When you add a new bridge, this get the name `pulse_out-1` and even if you set "no_connection" it will get connected to the next ports available after `pulse_out`.

If you set "no connection" to `pulse_out` then `pulse_out-1` will respect the "no connection" option.

This is because the name of the bridge match some part of the string, if I change the name of the second bridge to "AUX-out_pulse", then this bridge can have it's own config.

Example
```
        "outputs": {
            "pulse_out": {
                "connection": "monitor",
                "count": 2
            },
            "pulse_outAUX": {
                "connection": "none",
                "count": 2
            }
  
```          
This will do `pulse_out -> system:playback_1-2` + ` pulse_outAUX -> system:playback_3-4`

And this
```
        "outputs": {
            "pulse_out": {
                "connection": "monitor",
                "count": 2
            },
            "pulse_outAUX": {
                "connection": "system:playback_7",
                "count": 2
            }
  
```
Will do `pulse_out -> system:playback_1-2` +  `pulse_outAUX -> system:playback_3-4`  +  `pulse_outAUX -> system:playback_7-8`

**Comment by ovenwerks** [comment]
Is this version 2.1.2 or 2.1.3? This looks very much like the bug that 2.1.3 (released yesterday) fixed.

**Comment by Marzal** [comment]
2.1.3.r0.ga9edf93 from git

**Comment by ovenwerks** [comment]
confirmed, apparently the jack regex in find ports does not see :

**Comment by ovenwerks** [comment]
release 2.1.4 should have fixed this (does here)
