### ISSUE TITLE
USB device menu doesn't show new device until another menu entry selected

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#6]
Possibly automatically when the dropdown is opened, manually via a button pressed by the user, or automatically by watching for changes?

**Comment by ovenwerks** [comment]
If a USB device is plugged in or unplugged The device list is already refreshed. If logging is set to debug at least the logfile should show that autojack knows about a new device or a vanishing device. It sends a message to studio-controls (if it is running). If this is not happening then the dbus message I am listening for may be different or not exist. As I can't know how _every_ distro does this I can add a refresh button but I would like to know a better way (more universal) of detecting USB plug events. udev or acpi events are ok too.

**Comment by eeickmeyer** [comment]
@mxmilkiib You might make sure your packaging depends on jack2-dbus (or equivalent).

**Comment by mxmilkiib** [comment]
I'm fairly dbus ignorant. The file listing for package `jack2-git` includes `/usr/share/dbus-1/services/org.jackaudio.service`, and the official Arch [jack2](https://www.archlinux.org/packages/community/x86_64/jack2/) has a Replaces for `jack2-dbus`, and I think I remember @dvzrv spearheaded sorting all the packing out a while back, so I think things should be equivalent (but obviously not exactly enough somehow).

I notice now that it does update with the new device, but only after another item in the menu has been selected.

**Comment by ovenwerks** [comment]
@mxmilkiib Could I get you to set debugging to extra (I need to change the debug levels) and then plug and unplug a usb device. After that if you could attach ~/.log/autojack.log to this bug. Also if you run studio-controls from a terminal, you should see "autojack sees usb change" in the terminal every time a usb audio device is plugged in or out. This should not depend on which jackd binary you have but I do not know if arch throws the same dbus signal when a USB device is plugged/unplugged. before I can fix this I need to know what arch does.

**Comment by mxmilkiib** [comment]
Interesting; crossover with the loopback issue; in the Extra Devices>Connect Other.., selecting each loopback device one by one instantly makes the chosen option go back to Add (Available) and then optning the menu again and that loopback device is gone.

Hmm, I set to Extra, quit, deleted the log, turned my Reloop Beatmix 4 off, started, turning it on, seeing no change in the 'USB device that should be Master', selecting my H6 or none, seeing the Beatmix4 appear, turning if off, seeing no change, choosing either alternative, seeing the menu options change after that point, quit, but the ~/.log/autojack.log is empty.

**Comment by ovenwerks** [comment]
@mxmilkiib  wrote: "but the ~/.log/autojack.log is empty."  This seems like more of a problem to me. My first guess is that maybe autojack is not running at all? what does the output look like if you run autojack from the command line? (attach here) Does it keep going or quit? (It should keep going). In studio_controls in the "system tweaks" tab there is a dropdown for "Logging Level" this should be set to "Extra" so there is output to ~/.log/autojack.log... though even at info there should be some.

**Comment by ovenwerks** [comment]
Because I have not gotten the requested information, I am assuming this issue has worked itself out

**Comment by mxmilkiib** [comment]
Apologies, got distracted, now my laptop has died so it will be longer until I check this. (That is if I could figure out how to cleanly and quickly transition between a JACK and PipeWire environment.)

A suggestion though would be to add information about exactly what autojack is for, etc., to the README.
