### ISSUE TITLE
query xruns over dbus instead of of libjack

### ISSUE THREAD

**Issue by falkTX** [ovenwerks/studio-controls#62]
In commit https://github.com/ovenwerks/studio-controls/commit/d16f043d10b1fdc53bd4c09c04c83c3dc996a600 a jack xrun callback is registered.
this causes jack to call into this python function when an xrun happens, which can actually cause the audio to glitch out more (afaik jack will wait until all xrun callbacks are triggered and only after resume with audio playback)

Since studio-controls is already using dbus, consider using that for fetching xrun info as well.
There are `GetXruns` and `ResetXruns` methods in `/org/jackaudio/Controller` with interface `org.jackaudio.JackControl`.
Please use them.

**Comment by ovenwerks** [comment]
Thank you. Is there somewhere I can find documentation for jackdbus' dbus interface? The only documentation I have been able to find is jack_control. I am wondering if there any other dbus bits I should be using. Fixed in Commit: 6d1b54aabd128d70d498bb79f46abf9f958daedd

**Comment by falkTX** [comment]
just use any dbus instrospection tool, like qdbusviewer.
it will list all available methods
