### ISSUE TITLE
Add commnd line options for a2jmidid

### ISSUE THREAD

**Issue by Stazed** [ovenwerks/studio-controls#63]
The command line a2jmidid -u is really necessary for session use with alsa midi.

**Comment by ovenwerks** [comment]
Should this be switchable or is -u a good general setting?

**Comment by Stazed** [comment]
It should probably be switchable. I personally use -u always, but there are likely others who would not want it. There are other command line options also, which I do not use.

**Comment by ovenwerks** [comment]
This has been added in 2.2.9

**Comment by Stazed** [comment]
Thank you!!!!
