### ISSUE TITLE
Studio Controls 2.2 fails to start and exits silently with "KeyError: 'firewire'"

### ISSUE THREAD

**Issue by iso-l588** [ovenwerks/studio-controls#65]
After upgrading to studio-controls 2.2 the program fails to start.

When trying from the system menu it silently does nothing, when starting from terminal I get this output:

> install path: /usr
> Config file: /home/user/.config/autojack/autojack.json
> Traceback (most recent call last):
>   File "/usr/bin/studio-controls", line 1831, in <module>
>     us = StudioControls()
>   File "/usr/bin/studio-controls", line 600, in __init__
>     self.refresh_dropdowns()
>   File "/usr/bin/studio-controls", line 850, in refresh_dropdowns
>     if dev_db['firewire']:
> KeyError: 'firewire'

My system has no firewire devices. I am running Kubuntu 20.04 with the Ubuntu Studio installer on an HP ZBook15 G3.

I tried to install the 2.1.71 but it seems I failed to make a parallell install which messed up - apparently I'm still running 2.2. I uninstalled 2.2 (which also removed ubuntustudio-installer, ubuntustudio-branding-common, ubuntustudio-menu and ubuntustudio-menu-add) and tried again, extracting the 2.1.71 beta to a directory and "sudo make install". It fails with

> make links
> ln -s /usr/local/lib/systemd/system/studio-system.service \
>         /usr/local/lib/systemd/system/multi-user.target.wants/studio-system.service
> ln: failed to create symbolic link '/usr/local/lib/systemd/system/multi-user.target.wants/studio-system.service': File exists
> make: *** [Makefile:67: install] Error 1

I need some help here: what is the proper way to downgrade studio-controls?

(apologies if editing creates multiple mails to folks - I missed the preview tab!)

**Comment by ovenwerks** [comment]
If you just did a make install with no PREFIX=/usr it is likely 2.2.1 is installed in /usr/local/* It would have been better to wait for the package to arrive. I would uninstall 2.2.1, if you can, then, because you are running 20.04 you should be able to use muon to select the last non-ppa version.

It is ok that you have no firewire device. In that case the firewire key should be False. But it still needs to be there so controls knows you don't have any FW device. I have not been able to duplicate your results, but have chosen to make sure the detection is only made if the key exists anyway.

**Comment by iso-l588** [comment]
"apt search studio-controls" still shows 2.2 as available

`studio-controls/focal,focal,now 2.2.0-0ubuntu1~ubuntu20.04.1~ppa1 all [residual-config]`
`Studio Controls - Jack Audio Configuration Tool`

I will download 2.2.1 from here and give it a try

**Comment by iso-l588** [comment]
So I downloaded 2.2.1 and extracted to a home folder.
`sudo make install` failed in the same way as previously described while `sudo make install PREFIX=/usr` seemingly went well.
Then `studio-controls` returned this:

```
install path: /usr/local
Config file: /home/user/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/local/bin/studio-controls", line 1836, in <module>
    us = StudioControls()
  File "/usr/local/bin/studio-controls", line 602, in __init__
    self.refresh_dropdowns()
  File "/usr/local/bin/studio-controls", line 888, in refresh_dropdowns
    desc_base = f"{this_dev} {dev_db['id']} {dev_db['bus']} {dev_db['raw']},{this_sub},0"
KeyError: 'id'
```

But since you can't reproduce, maybe something in my setup went haywire?

I also downloaded 2.1.4 since it was the last one working for me. Curiously, `sudo make install PREFIX=/usr` fails with

```
# make links
ln -s /usr/lib/systemd/system/studio-system.service \
        /usr/lib/systemd/system/multi-user.target.wants/studio-system.service
ln: failed to create symbolic link '/usr/lib/systemd/system/multi-user.target.wants/studio-system.service': File exists
make: *** [Makefile:67: install] Error 1

```

while `sudo make install` works just fine. 2.1.4 still works for me after this.

**Comment by ovenwerks** [comment]
For those seeing this problem, The script that is at fault is convert-studio-controls which fails to write the new config file. I am away from computers till September but should be able to fix this then.

**Comment by ovenwerks** [comment]
This issue should finally be fixed with 2.2.3

**Comment by ovenwerks** [comment]
No more comments for 22 days. Am guessing this is fixed as above

**Comment by lootre** [comment]
Hi !

I'm having trouble with Studio-controls that are strangely similar to this issue, even though I'm running version 2.2.7 on UbuntuStudio 21.10 (fresh install).

Here is my terminal output:

```
toma@toma-studio:~$ studio-controls

(studio-controls:4585): Gtk-WARNING **: 19:48:10.251: Locale not supported by C library.
        Using the fallback 'C' locale.
install path: /usr
Config file: /home/toma/.config/autojack/autojack.json
Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1837, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 555, in __init__
    self.devdb.scan_dev(self.conf_db)
  File "/usr/bin/studio-controls", line 164, in scan_dev
    if usb and [ conf['devices'][dev]['id'], conf['devices'][dev]['bus'] ] == [ d_id, bus ]:
KeyError: 'id'
```

As you can see, I have the same error than @iso-l588 

It was running fine on UbuntuStudio 21.04.

Thanks for your help !

**Comment by lootre** [comment]
I just tested to launch studio-controls with admin privileges and it starts, however it does not have the real-time permission activated and starting Jack is also done in admin, meaning I can't use it with the standard user profile.

**Comment by ovenwerks** [comment]
On Mon, 18 Oct 2021, lootre wrote:

> As you can see, I have the same error than @iso-l588

It is not the same error. Please open a new issue.

Also be aware that once an issue is closed, it no longer appears on my 
list of valid issues.

--
Len Ovens
www.ovenwerks.net

**Comment by lootre** [comment]
My apologies, you're right it's not the same issue... I found the answer to mine on another forum. Sorry again and thanks for your answer.
