### ISSUE TITLE
Source code for Debian

### ISSUE THREAD

**Issue by oscarsantis** [ovenwerks/studio-controls#66]
Is there a version of the studio-controls source code to compile on Debian 11?

**Comment by ovenwerks** [comment]
There is no compile step as this is all python scripts. Packaging is left up to the distrobution but in this case the ubuntu package may just work.

**Comment by stevenjaycohen** [comment]
Confirmed! Studio Controls for Ubuntu 20.04 installs and functions on Debian 11 without issue!
