### ISSUE TITLE
Display loopback devices after physical devices in device menus?

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#7]
I think that listing any physical cards/devices before any Loopback devices in the device dropdown menus on the JACK Master and Extra Devices tabs would be less confusing to users.

**Comment by ovenwerks** [comment]
I am not sure what you mean in this case. What do you mean by loopback devices? The devices are all the devices listed in /proc/asound/cards file. Can you attach what the drop down looks like (screen shot) with loopback devices and also /proc/asound/cards if the loopback devices show up in this file... the devices are listed from card _0_ to card _n_ in numerical order right now.

**Comment by mxmilkiib** [comment]
![image](https://user-images.githubusercontent.com/108225/98265329-e00aa100-1f80-11eb-83d4-79481c182211.png)

```
% cat /proc/asound/cards
 0 [Loopback       ]: Loopback - Loopback
                      Loopback 1
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7c00000 irq 38
 2 [BeatMix4       ]: USB-Audio - BeatMix4
                      RELOOP BeatMix4 at usb-0000:00:1a.0-1.3.2.2, full speed
```

```
% aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 0: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: PCH [HDA Intel PCH], device 0: ALC269VB Analog [ALC269VB Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: BeatMix4 [BeatMix4], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #1 
```

![image](https://user-images.githubusercontent.com/108225/98265754-61faca00-1f81-11eb-9b54-cb3569f02807.png)

**Comment by ovenwerks** [comment]
Thank you, I can work with that.

**Comment by ovenwerks** [comment]
I am wondering if the loopback devices should even appear in these menus at all. Can Jack use one of these loopback devices as jack master? Would someone use them as headphones, or extra devices? I think for now:
jack master: no loopback in dropdown
headphone: no loopback in dropdown
add and remove: put loopbacks at bottom

**Comment by ovenwerks** [comment]
A fix has been made does it work as expected now?
