### ISSUE TITLE
Alsa2Jack Midi Bridge not activated automatically (2 trials needed typically)

### ISSUE THREAD

**Issue by codecollider** [ovenwerks/studio-controls#70]
Hi,

I'm using Ubuntustudio 20.04. Not sure if this is normal behavior, but the Alsa2Jack Midi Bridge  is not activated when Studio Controls is started although the appropriate box under Jack Master Settings is checked. I need to deactivate it --> apply settings and activate it again --> apply settings to get it working properly .

**Comment by ovenwerks** [comment]
On Sun, 31 Oct 2021, codecollider wrote:

> I'm using Ubuntustudio 20.04. Not sure if this is normal behavior, but the
> Alsa2Jack Midi Bridge is not activated when Studio Controls is started

Not normal behaviour. Also not an issue here.

However, more information is needed. In the System Tweaks tab of Studio 
Controls, please set Logging Level to Extra. Then run autojack from a 
terminal. Please paste the output from this run as well as the contents 
of:
~/.log/autojack.log
to this bug.

Also, please add the version of studio-controls you are using. In all 
recent versions of studio-controls, the version is listed at the top of 
the studio-controls window. The current version is 2.2.7.

--
Len Ovens
www.ovenwerks.net

**Comment by codecollider** [comment]
Hi, 

thanks for the quick response. I'm on version 2.2.7 as well. 
Here's the link to the log file (today I activated extra logging level) and at around 16:10 I rebooted:

https://e.pcloud.link/publink/show?code=XZLS7JZ7Tv752zKA304injkuafnr79Rl7w7

When starting studiocontrols from the terminal I only get:

:/etc$ studio-controls
install path: /usr
Config file: /home/marco/.config/autojack/autojack.json
initialization complete
autojack is running

That's the option I'm talking about
https://imgur.com/AhUIunB.png

As interface I only use an UMC 204 Behringer interface.

**Comment by ovenwerks** [comment]
On Mon, 1 Nov 2021, codecollider wrote:

> thanks for the quick response. I'm on version 2.2.7 as well.
> Here's the link to the log file (today I activated extra logging level) and
> at around 16:10 I rebooted:
> 
> https://e.pcloud.link/publink/show?code=XZLS7JZ7Tv752zKA304injkuafnr79Rl7w7

In this I find that the config file has:
     "pulse": {
         "inputs": {
             "pulse_in": {
                 "connection": "1",
                 "count": 2
             }
         },
         "outputs": {
             "pulse_out": {
                 "connection": "1",
                 "count": 2
             }
         }
     },

this:
"connection": "1",
is causing the problem. It is not your problem but it shows a case we have 
not thought of when updating the config file. This will be fixed in the 
next release. However, in the mean time, you can in Studio controls->Pulse 
Bridging->Remove This Bridge.
Do this for both of the bridges (in and out) and then add the bridges back 
in with "Add A new Bridge" (one for in and one for out). Pulse_out can be 
connected to system:playback_1 and pulse_in (actually you can rename them 
to what suits you) can be connected to system:capture_1.

I am sorry the bug slipped by but it is one of those things was corrected 
some time ago that was missed when fixing other things.


--
Len Ovens
www.ovenwerks.net

**Comment by codecollider** [comment]
Hi,

thank you and thanks for fixing. I wonder though how the pulse bridge is related to the ALSA 2 JACK MIDI bridge which needs two trials until it shows up (in RaySession). Removing and adding the pulse bridges didn't change anything. As a (quicker) workaround I still can start the MIDI bridge from the terminal.

**Comment by ovenwerks** [comment]
On Tue, 2 Nov 2021, codecollider wrote:

> thank you and thanks for fixing. I wonder though how the pulse bridge is
> related to the ALSA 2 JACK MIDI bridge which needs two trials until it shows

When Jack is started it goes through a number of processes. It first 
configures jack and pulse, Then starts jack, then sets up pulse bridges 
before it starts a2j. So if anything fails before it gets to starting a2j, 
it just doesn't get that far.

> up (in RaySession). Removing and adding the pulse bridges didn't change
> anything. As a (quicker) workaround I still can start the MIDI bridge from
> the terminal.

Did you make sure to apply the changes? Anyway, assuming you did, It may 
be there is something else that has not be taken into account. So perhaps 
another log file paste will show where things have got to now.


--
Len Ovens
www.ovenwerks.net

**Comment by codecollider** [comment]
Just want to let you know after rebooting it suddenly works :) Thanks again!

**Comment by ovenwerks** [comment]
version 2.2.8 should fix this.
