### ISSUE TITLE
Studio-controls not launching on Ubuntu 21.10, KeyError: 'id' (LP: #1950817)

### ISSUE THREAD

**Issue by eeickmeyer** [ovenwerks/studio-controls#71]
Forwarded from [Launchpad Bug #1950817](https://bugs.launchpad.net/bugs/1950817)

> Hi,
> 
> I am using studio-controls 2.2.7-0ubuntu1 after having upgraded to Impish. Studio-controls fails to launch with the following traceback:
> 
> install path: /usr
> Config file: /home/steve/.config/autojack/autojack.json
> Traceback (most recent call last):
>   File "/usr/bin/studio-controls", line 1837, in <module>
>     us = StudioControls()
>   File "/usr/bin/studio-controls", line 555, in __init__
>     self.devdb.scan_dev(self.conf_db)
>   File "/usr/bin/studio-controls", line 164, in scan_dev
>     if usb and [ conf['devices'][dev]['id'], conf['devices'][dev]['bus'] ] == [ d_id, bus ]:
> KeyError: 'id'
> 
> Here is my system info:
> 
> Operating System: Kubuntu 21.10
> KDE Plasma Version: 5.22.5
> KDE Frameworks Version: 5.86.0
> Qt Version: 5.15.2
> Kernel Version: 5.13.0-21-lowlatency (64-bit)
> Graphics Platform: X11
> Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
> Memory: 15.3 GiB of RAM
> Graphics Processor: Mesa Intel® UHD Graphics 620
> 
> I do have the file autojack.json in .config/autojack that is referred to in another bug report.
> 
> After failing to launch, I have a studio-controls.lock file created in the .config/autojack directory. The studio-controls interface does not appear at any time.
> 
> Last point, I'm using Pipewire, as I was before upgrading to 21.10, which didn't create a problem with Studio-controls then. I would like to continue to use Studio-controls to control cpu performance and intel boost, and possibly other things.
> 
> Thanks !!
> 
> Stephen
> ---
> ProblemType: Bug
> ApportVersion: 2.20.11-0ubuntu71
> Architecture: amd64
> CasperMD5CheckResult: unknown
> CurrentDesktop: KDE
> DistroRelease: Ubuntu 21.10
> InstallationDate: Installed on 2020-09-18 (421 days ago)
> InstallationMedia: Kubuntu 20.04.1 LTS "Focal Fossa" - Release amd64 (20200731)
> Package: studio-controls 2.2.7-0ubuntu1
> PackageArchitecture: all
> ProcVersionSignature: Ubuntu 5.13.0-21.21-lowlatency 5.13.18
> Tags: impish third-party-packages
> Uname: Linux 5.13.0-21-lowlatency x86_64
> UpgradeStatus: Upgraded to impish on 2021-10-26 (19 days ago)
> UserGroups: adm audio cdrom dip lpadmin lxd plugdev sambashare sudo www-data
> _MarkForUpload: True

**Comment by ovenwerks** [comment]
Please try version 2.2.8. If that does not work, please include a paste of the output of convert-studio-controls run from the command line.

**Comment by eeickmeyer** [comment]
This was fixed, not sure why this wasn't closed.
