### ISSUE TITLE
Option to fully disable Pulse Bridges

### ISSUE THREAD

**Issue by KurosakiHT** [ovenwerks/studio-controls#72]
I don't want to use pulse bridge because I've configured pulseaudio manual sink. But if I manually remove pulse bridges in the GUI and then exit, I can't open the GUI again gave traceback:

Traceback (most recent call last):
  File "/usr/bin/studio-controls", line 1837, in <module>
    us = StudioControls()
  File "/usr/bin/studio-controls", line 605, in __init__
    self.refresh_pulse_tab(self.pj_bridge)
  File "/usr/bin/studio-controls", line 1315, in refresh_pulse_tab
    self.pj_direct.set_text('none')
AttributeError: 'StudioControls' object has no attribute 'pj_direct'

So yeah, I want an option to disable pulse bridges or at least let me configure the bridge like others GUI like Cadance

**Comment by ovenwerks** [comment]
That is a bug - fixed in next release.

A more complete description of "configure the bridge like others GUI like Cadance" would be nice too. I will not install cadence as it breaks the system and leaves it that way even when removed. Also a "reason why I want this".

**Comment by ovenwerks** [comment]
As of studio-controls 2.2.9, If no pulse-jack bridges are to be created, the alsa devices will still show in pulseaudio. The bug with things freezing when trying to have no pa-jack bridges should be fixed as well.
