### ISSUE TITLE
No module named 'jack' - however jack is installed

### ISSUE THREAD

**Issue by JRSV** [ovenwerks/studio-controls#73]
Hello,

I am trying to run studio-controls in AV-MX (debian 10). It compiles with no errors, but does not run. I get the following error

`Traceback (most recent call last):
  File "/usr/local/bin/studio-controls", line 9, in <module>
    import jack
ModuleNotFoundError: No module named 'jack'
`
any advice?

**Comment by ovenwerks** [comment]
On Tue, 28 Dec 2021, Jose Rafael Subia Valdez wrote:

> I am trying to run studio-controls in AV-MX (debian 10). It compiles with no
> errors, but does not run. I get the following error
> 
> Traceback (most recent call last): File "/usr/local/bin/studio-controls",
> line 9, in <module> import jack ModuleNotFoundError: No module named 'jack'
> any advice?

This is a packaging error. Please submit a debian bug for this requesting 
the packager to include all dependancies. It seems you are at least 
missing python3-jack-client. It may be that you are missing other packages 
as well.

Please note: we do not package this software, these kinds of bug reports 
should first go to the packager.

--
Len Ovens
www.ovenwerks.net

**Comment by JRSV** [comment]
Pardon my ignorance, but I did not installed it through packaging manager but compiled it myself.
so.. how is this a packaging error?? either way I will try installing that python package that I am missing.
