### ISSUE TITLE
please install qmidinet first, however it is installed.

### ISSUE THREAD

**Issue by JRSV** [ovenwerks/studio-controls#74]
I managed to get studio-controls working, and I have qmidinet installed, I also make sure it is running first. however in the network tab I get the "please install qmidinet first" message.

any advice on how to make studio-controls recognize the qmidinet installation?

cheers

**Comment by ovenwerks** [comment]
On Tue, 28 Dec 2021, Jose Rafael Subia Valdez wrote:

> I managed to get studio-controls working, and I have qmidinet installed, I
> also make sure it is running first. however in the network tab I get the
> "please install qmidinet first" message.

That may be a studio-controls bug. From a command line type:
which qmidinet
It should print out:
/usr/bin/qmidinet

Please let me know what your output is.

Also make sure it is installed as a *.deb package, not a flatpack or 
similar.

--
Len Ovens
www.ovenwerks.net

**Comment by JRSV** [comment]
ok, fixed by moving qmidinet from /usr/local/bin to /usr/bin.

now everything is a ok.!

cheers

**Comment by ovenwerks** [comment]
On Wed, 29 Dec 2021, Jose Rafael Subia Valdez wrote:

> ok, fixed by moving qmidinet from /usr/local/bin to /usr/bin.
> 
> now everything is a ok.!

I am glad you got it working. I will see what I can do about testing the 
path where programs reside instead of assuming /usr/bin/ in the next 
release.

--
Len Ovens
www.ovenwerks.net

**Comment by ovenwerks** [comment]
We now look in /usr/local/ as well
