### ISSUE TITLE
Session Management options

### ISSUE THREAD

**Issue by mxmilkiib** [ovenwerks/studio-controls#8]
I'm clicking both the "RaySession" and the "NSM" button but nothing is happening.

I then tried uninstalling RaySession then restarting Studio Controls, but the button remains clickable. How about checking $PATH to see which of the session management app options are installed and greying out those that aren't?

Might it be also be possible to add Agordejo to the list?

**Comment by ovenwerks** [comment]
WIP Any time there has not yet been a tag... things may be broken. Things should not crash but new features may not work as expected. Session management is not something I personally use so hints on what to add are helpful. Agordejo can be added.

**Comment by eeickmeyer** [comment]
Just to dovetail on what @ovenwerks said, Agordejo is packaged and ready for Ubuntu Hirsute, at which time I'll backport it to Groovy and Focal in the Ubuntu Studio Backports PPA. I realize that this doesn't affect other distros, but it definitely puts it on the radar.

**Comment by ovenwerks** [comment]
I don't have Agordejo, can one of you tell me what the path to start it is? I assume /usr/bin/agordejo but the actual output of whereis would be helpful

**Comment by ovenwerks** [comment]
Added, but needs testing. If it works now feel free to close issue ;)

**Comment by mxmilkiib** [comment]
That works, in the general sense.

I remember now that I actually have a `~/bin/nsm` script with `agordejo --session-root ~/media/audio/projects/NSM` in it, to avoid creating an 'NSM Sessions' directory in my home.

Regarding the order of the three buttons; RaySession has the most advanced features, but unilateraly strays from the NSM API in a way that isn't backward compatible/portable. Agordejo is more advanced than the nsm-legacy app (which is just the reference frontend GUI). The current button order doesn't seem right, but I wouldn't know how to replace it atm. Possibly larger tooltips explaining the differences?

**Comment by ovenwerks** [comment]
I am not really a session manager user and pretty let them fall where they may. Certainly open to suggestions on this. (both button order and tooltips)

**Comment by ovenwerks** [comment]
The order has been changed.
