### ISSUE TITLE
Enabled PPA, Studio Controls uninstalled

### ISSUE THREAD

**Issue by Smaasten** [ovenwerks/studio-controls#82]
My Studio controls got uninstalled when I added the PPA.
https://launchpad.net/~ubuntustudio-ppa/+archive/ubuntu/backports
I reinstalled Studio Controls ( 2.3.0 ) , got the error, so removed it again and installed "Ubuntu Studio Installer"
and now it does not launch studio control and jack at startup. Ubuntu Studio 21.10.
![20220703_143632](https://user-images.githubusercontent.com/35669862/177083639-0dd35822-ba21-419b-8ca8-64bcef66b729.jpg)

I get this warning." Real time permission have not been properly installed " 
When I hit "Start or restart Jack" it starts and run like it should. But I would like to get that warning fixed and it doesn't help when I press " Fix Real Time Permissions ".
What do I do to fix this? If you need any kind of info, let me know and I will add it asap! 

Hope to hear from you.

**Comment by eeickmeyer** [comment]
I'm just going to give you a huge, gigantic warning: Ubuntu Studio 21.10 reaches end-of-life on July 14th (just a little over a week). You need to upgrade to Ubuntu Studio 22.04 LTS before then. That will give you a newer Studio Controls (and an even newer one via the backports PPA).

Your issues are likely fixed as you're running an ancient version of Studio Controls.

**Comment by ovenwerks** [comment]
ubuntu installation and problems is not something we deal with here and should be addressed with a ubuntu bug report.
